service: turbo-native-directory

image: robzolkos/turbonativedirectory

servers:
  web:
    hosts:
      - 5.161.197.35

registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY

volumes:
  - storage:/rails/storage

builder:
  arch:
    - amd64
