service: hotwire-native-directory

image: robzolkos/hotwirenativedirectory

servers:
  - 5.161.197.35

proxy:
  ssl: true
  hosts: turbonative.directory,hotwirenative.directory

registry:
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY

volumes:
  - storage:/rails/storage

builder:
  arch:
    - amd64
